<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:ax2135="http://data.service.webservices.workforcesoftware.com/xsd"
    xmlns:ax2138="http://webservices.workforcesoftware.com/xsd"
    xmlns:ns="http://services.workforcesoftware.com/xsd"
    xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://org.apache.axis2/xsd"
    xmlns:ax2134="http://ws.apache.org/axis2/xsd" xmlns:tns="http://services.workforcesoftware.com"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    targetNamespace="http://services.workforcesoftware.com">
    <wsdl:documentation>E2G_getPeriods_by_EmpId</wsdl:documentation>
    <wsdl:types>
        <xs:schema xmlns:ax2136="http://data.service.webservices.workforcesoftware.com/xsd"
            xmlns:ax2139="http://webservices.workforcesoftware.com/xsd"
            attributeFormDefault="qualified" elementFormDefault="qualified"
            targetNamespace="http://ws.apache.org/axis2/xsd">
            <xs:import namespace="http://data.service.webservices.workforcesoftware.com/xsd" />
            <xs:import namespace="http://webservices.workforcesoftware.com/xsd" />
            <xs:complexType name="E2g_period_data_request_by_empid">
                <xs:sequence>
                    <xs:element minOccurs="0" name="employeeId" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="numberOfPriorPeriods" nillable="true"
                        type="xs:int" />
                    <xs:element minOccurs="0" name="requestDate" nillable="true"
                        type="ax2135:WSDate" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2G_getPeriods_by_EmpIdResult">
                <xs:complexContent>
                    <xs:extension base="ax2138:WSResultObjectBase">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="result" nillable="true"
                                type="ax2134:E2g_period_data_list_by_empid" />
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="E2g_period_data_list_by_empid">
                <xs:sequence>
                    <xs:element minOccurs="0" name="periodMetaData" nillable="true"
                        type="ax2134:E2g_time_sheet_meta_data" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="periods" nillable="true"
                        type="ax2134:E2g_period_data" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_time_sheet_meta_data">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="fieldLabels"
                        nillable="true" type="ax2134:E2g_field_label" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="payCodes" nillable="true"
                        type="ax2134:E2g_pay_code" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_field_label">
                <xs:sequence>
                    <xs:element minOccurs="0" name="field" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="label" nillable="true" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_pay_code">
                <xs:sequence>
                    <xs:element minOccurs="0" name="payCode" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="payCodeType" nillable="true" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_period_data">
                <xs:sequence>
                    <xs:element minOccurs="0" name="managerApproval" nillable="true"
                        type="xs:string" />
                    <xs:element minOccurs="0" name="periodId" nillable="true"
                        type="ax2134:E2g_time_sheet_id" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="scheduleDetailRow"
                        nillable="true" type="ax2134:E2g_schedule_detail_row" />
                    <xs:element minOccurs="0" name="submittedByEmployee" nillable="true"
                        type="xs:boolean" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="timeSheetDetailRow"
                        nillable="true" type="ax2134:E2g_time_sheet_detail_row" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="timeSheetException"
                        nillable="true" type="ax2134:E2g_time_sheet_exception" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_time_sheet_id">
                <xs:sequence>
                    <xs:element minOccurs="0" name="assignmentInfo" nillable="true"
                        type="ax2134:E2g_assignment_info" />
                    <xs:element minOccurs="0" name="payPeriodBeginDate" nillable="true"
                        type="ax2135:WSDate" />
                    <xs:element minOccurs="0" name="payPeriodEndDate" nillable="true"
                        type="ax2135:WSDate" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_assignment_info">
                <xs:sequence>
                    <xs:element minOccurs="0" name="assignmentDescription" nillable="true"
                        type="xs:string" />
                    <xs:element minOccurs="0" name="assignmentId" nillable="true"
                        type="ax2135:WSGeneratedId" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_schedule_detail_row">
                <xs:sequence>
                    <xs:element minOccurs="0" name="amount" nillable="true" type="xs:double" />
                    <xs:element minOccurs="0" name="comments" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="endDateTime" nillable="true"
                        type="ax2135:WSDateTime" />
                    <xs:element minOccurs="0" name="hours" nillable="true" type="xs:int" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="ld" nillable="true"
                        type="xs:string" />
                    <xs:element minOccurs="0" name="payCode" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="startDateTime" nillable="true"
                        type="ax2135:WSDateTime" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="unit" nillable="true"
                        type="xs:double" />
                    <xs:element minOccurs="0" name="workDate" nillable="true" type="ax2135:WSDate" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_time_sheet_detail_row">
                <xs:sequence>
                    <xs:element minOccurs="0" name="amount" nillable="true" type="xs:double" />
                    <xs:element minOccurs="0" name="comments" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="endDateTime" nillable="true"
                        type="ax2135:WSDateTime" />
                    <xs:element minOccurs="0" name="hours" nillable="true" type="xs:double" />
                    <xs:element minOccurs="0" name="inSwipeLatitude" nillable="true"
                        type="xs:double" />
                    <xs:element minOccurs="0" name="inSwipeLongitude" nillable="true"
                        type="xs:double" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="ld" nillable="true"
                        type="xs:string" />
                    <xs:element minOccurs="0" name="outSwipeLatitude" nillable="true"
                        type="xs:double" />
                    <xs:element minOccurs="0" name="outSwipeLongitude" nillable="true"
                        type="xs:double" />
                    <xs:element minOccurs="0" name="payCode" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="startDateTime" nillable="true"
                        type="ax2135:WSDateTime" />
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="unit" nillable="true"
                        type="xs:double" />
                    <xs:element minOccurs="0" name="workDate" nillable="true" type="ax2135:WSDate" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="E2g_time_sheet_exception">
                <xs:sequence>
                    <xs:element minOccurs="0" name="code" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="date" nillable="true" type="ax2135:WSDate" />
                    <xs:element minOccurs="0" name="message" nillable="true" type="xs:string" />
                    <xs:element minOccurs="0" name="severity" nillable="true"
                        type="ax2134:Exception_severityChoice" />
                    <xs:element minOccurs="0" name="temporaryExceptionKey" nillable="true"
                        type="ax2135:WSGeneratedId" />
                    <xs:element minOccurs="0" name="type" nillable="true" type="ax2135:WSPolicyId" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="Exception_severityChoice">
                <xs:complexContent>
                    <xs:extension base="ax2135:WSChoiceBase">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="exception_severity" nillable="true"
                                type="xs:string" />
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
        </xs:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
            targetNamespace="http://data.service.webservices.workforcesoftware.com/xsd">
            <xs:complexType name="WSDate">
                <xs:sequence>
                    <xs:element minOccurs="0" name="day" type="xs:int" />
                    <xs:element minOccurs="0" name="month" type="xs:int" />
                    <xs:element minOccurs="0" name="year" type="xs:int" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="WSGeneratedId">
                <xs:sequence>
                    <xs:element minOccurs="0" name="id" type="xs:long" />
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="WSDateTime">
                <xs:complexContent>
                    <xs:extension base="ax2135:WSDate">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="hours" type="xs:int" />
                            <xs:element minOccurs="0" name="minutes" type="xs:int" />
                            <xs:element minOccurs="0" name="seconds" type="xs:int" />
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:complexType name="WSChoiceBase">
                <xs:sequence />
            </xs:complexType>
            <xs:complexType name="WSPolicyId">
                <xs:sequence>
                    <xs:element minOccurs="0" name="policyId" nillable="true" type="xs:string" />
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
            targetNamespace="http://webservices.workforcesoftware.com/xsd">
            <xs:complexType name="WSResultObjectBase">
                <xs:sequence>
                    <xs:element minOccurs="0" name="detailedErrorMessage" nillable="true"
                        type="xs:string" />
                    <xs:element minOccurs="0" name="operationSuccessful" type="xs:boolean" />
                    <xs:element minOccurs="0" name="resultCode" type="xs:int" />
                    <xs:element minOccurs="0" name="resultDescription" nillable="true"
                        type="xs:string" />
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
        <xs:schema xmlns:ax2137="http://ws.apache.org/axis2/xsd" attributeFormDefault="qualified"
            elementFormDefault="qualified"
            targetNamespace="http://services.workforcesoftware.com/xsd">
            <xs:import namespace="http://ws.apache.org/axis2/xsd" />
            <xs:element name="E2G_getPeriods_by_EmpId">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="request" nillable="true"
                            type="ax2137:E2g_period_data_request_by_empid" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="E2G_getPeriods_by_EmpIdResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="return" nillable="true"
                            type="ax2137:E2G_getPeriods_by_EmpIdResult" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="E2G_getPeriods_by_EmpIdRequest">
        <wsdl:part name="parameters" element="ns:E2G_getPeriods_by_EmpId" />
    </wsdl:message>
    <wsdl:message name="E2G_getPeriods_by_EmpIdResponse">
        <wsdl:part name="parameters" element="ns:E2G_getPeriods_by_EmpIdResponse" />
    </wsdl:message>
    <wsdl:portType name="E2G_getPeriods_by_EmpIdPortType">
        <wsdl:operation name="E2G_getPeriods_by_EmpId">
            <wsdl:input message="tns:E2G_getPeriods_by_EmpIdRequest"
                wsaw:Action="urn:E2G_getPeriods_by_EmpId" />
            <wsdl:output message="tns:E2G_getPeriods_by_EmpIdResponse"
                wsaw:Action="urn:E2G_getPeriods_by_EmpIdResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="E2G_getPeriods_by_EmpIdSoap11Binding"
        type="tns:E2G_getPeriods_by_EmpIdPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="E2G_getPeriods_by_EmpId">
            <soap:operation soapAction="urn:E2G_getPeriods_by_EmpId" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="E2G_getPeriods_by_EmpIdSoap12Binding"
        type="tns:E2G_getPeriods_by_EmpIdPortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="E2G_getPeriods_by_EmpId">
            <soap12:operation soapAction="urn:E2G_getPeriods_by_EmpId" style="document" />
            <wsdl:input>
                <soap12:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="E2G_getPeriods_by_EmpIdHttpBinding"
        type="tns:E2G_getPeriods_by_EmpIdPortType">
        <http:binding verb="POST" />
        <wsdl:operation name="E2G_getPeriods_by_EmpId">
            <http:operation location="E2G_getPeriods_by_EmpId" />
            <wsdl:input>
                <mime:content type="application/xml" part="parameters" />
            </wsdl:input>
            <wsdl:output>
                <mime:content type="application/xml" part="parameters" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="E2G_getPeriods_by_EmpId">
        <wsdl:port name="E2G_getPeriods_by_EmpIdHttpsSoap11Endpoint"
            binding="tns:E2G_getPeriods_by_EmpIdSoap11Binding">
            <soap:address
                location="https://origin-dev.au.wfs.cloud/workforce/services/E2G_getPeriods_by_EmpId.E2G_getPeriods_by_EmpIdHttpsSoap11Endpoint/" />
        </wsdl:port>
        <wsdl:port name="E2G_getPeriods_by_EmpIdHttpSoap11Endpoint"
            binding="tns:E2G_getPeriods_by_EmpIdSoap11Binding">
            <soap:address location="" />
        </wsdl:port>
        <wsdl:port name="E2G_getPeriods_by_EmpIdHttpSoap12Endpoint"
            binding="tns:E2G_getPeriods_by_EmpIdSoap12Binding">
            <soap12:address location="" />
        </wsdl:port>
        <wsdl:port name="E2G_getPeriods_by_EmpIdHttpsSoap12Endpoint"
            binding="tns:E2G_getPeriods_by_EmpIdSoap12Binding">
            <soap12:address
                location="https://origin-dev.au.wfs.cloud/workforce/services/E2G_getPeriods_by_EmpId.E2G_getPeriods_by_EmpIdHttpsSoap12Endpoint/" />
        </wsdl:port>
        <wsdl:port name="E2G_getPeriods_by_EmpIdHttpEndpoint"
            binding="tns:E2G_getPeriods_by_EmpIdHttpBinding">
            <http:address location="" />
        </wsdl:port>
        <wsdl:port name="E2G_getPeriods_by_EmpIdHttpsEndpoint"
            binding="tns:E2G_getPeriods_by_EmpIdHttpBinding">
            <http:address
                location="https://origin-dev.au.wfs.cloud/workforce/services/E2G_getPeriods_by_EmpId.E2G_getPeriods_by_EmpIdHttpsEndpoint/" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>